import { dbConnect } from "@/database/dbConnect";
import "../globals.css";
import Navbar from "@/components/ui/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body>
        <main>
          <Navbar mode={false} />
        </main>
        {children}
      </body>
    </html>
  );
}
